### ISSUE TITLE
Merge both files in one

### ISSUE THREAD

**Issue by abhishalya** [TheComputerM/julia-games#3]
Ideally, a user should only be asked to run a single file. Currently, the tic-tac-toe game has two different files and they should be merged into one such that the new file would call functions as required based on the game mode the user selects.

**Comment by TheComputerM** [comment]
@abhishalya  I don't see a problem with the existing approach, It should be obvious that if a person knows about julia they should at least know about the CLI and installing the game is properly documented. I made the game into separate files so that the code base is neat, tidy and easy for people to understand. I will add comments to both the game files.

**Comment by abhishalya** [comment]
You can keep the files as you'd like, but you can add a new file which would take care of invoking the respective file based on the game mode. This would make for a much better experience for the user imo. :)
